### ISSUE TITLE
problem with firefox browser

### ISSUE THREAD

**Issue by MHA15** [thibaultboursier/use-timer#7]
hello 
thanks to your good library 

there is a problem with Firefox browser that seems it is because of that your `setTimeout ` will run before `setInterval` and then decreasing counter will stuck in second 1 and will never get to zero 

I will be happy to inform me when this bug fixed

**Comment by thibaultboursier** [comment]
Hello @MHA15 

Thanks for opening this issue.
Could you, please, reproduce this problem, on [Stackblitz](https://stackblitz.com/) for example, and share the link?

Thanks.

**Comment by MHA15** [comment]
> Hello @MHA15
> 
> Thanks for opening this issue.
> Could you, please, reproduce this problem, on [Stackblitz](https://stackblitz.com/) for example, and share the link?
> 
> Thanks.

thanks for your response I had write it simply in [this linke](https://codesandbox.io/embed/nervous-albattani-ngkvj?fontsize=14&hidenavigation=1&theme=dark) 
in chrome it will increase to 0 but in firefox it will stuck on second 1 


I thinks that you should check finishing in interval and no need to use timeout function

**Comment by MHA15** [comment]
another idea is to use `setTimeout` with +1 millisecond 
can you fix it soon? 
i would be happy to make a PR for it?

**Comment by thibaultboursier** [comment]
Thanks for your example. I was able to reproduce it.
As explained [here](https://stackoverflow.com/a/29972322/5908790) about timers,  

> They cannot be trusted, there are no accuracy guarantees for them. They are allowed to lag arbitrarily, and they do not keep a constant pace but tend to drift (as you have observed).

The drift is different between Firefox and Chrome.
I can't check finishing inside interval, because i don't have access to last time value, due to **closure**. But there are some interesting resources about creating an accurate timer:
- https://www.sitepoint.com/creating-accurate-timers-in-javascript/
- https://medium.com/@swainson/accurate-javascript-timers-f71e0af5df32

We should rely on **Date object** or, better, **Performance API**.
For now, in order to fix temporarily this problem, we could **increase setTimeout delay,** as you said, by adding part of the interval.

Example:

```js
const driftDelay = delay * 0.25;
const delay = Math.abs(endTime - (pausedTimeRef.current || initialTime)) * interval + driftDelay;
```
Could you create a PR for that?

**Comment by thibaultboursier** [comment]
I have a simpler solution, which does not need any setTimeout.

```js
  useEffect(() => {
    if (endTime === null) {
      return;
    }

    if (time === endTime) {
      cancelInterval();
      setShouldResetTime(true);
    }
  }, [endTime, time]);
```

Inside effect, we just check if endTime is reached, and if it's the case, we cancel interval timer.
createTimeout method can be deleted so.

Can you implement that and check if there is no regression, please? I just looked and unit test pass.

**Comment by thibaultboursier** [comment]
@MHA15 any update?

**Comment by MHA15** [comment]
> I have a simpler solution, which does not need any setTimeout.
> 
> ```js
>   useEffect(() => {
>     if (endTime === null) {
>       return;
>     }
> 
>     if (time === endTime) {
>       cancelInterval();
>       setShouldResetTime(true);
>     }
>   }, [endTime, time]);
> ```
> 
> Inside effect, we just check if **endTime is reached,** and if it's the case, we cancel interval timer.
> createTimeout method can be deleted so.
> 
> **Can you implement that and check if there is no regression, please? I just looked and unit test pass.**

I don't think that using an effect hook be a good idea (effect hook will not run sync and we shouldn't trust on it) 


> I can't check finishing inside interval, because i don't have access to last time value, due to **closure**. But there are some interesting resources about creating an accurate timer:
I didn't understand what is the problem? why couldn't we check time value inside of interval?

**Comment by thibaultboursier** [comment]
Make the test and try to access last time value inside interval: it will not work because of closure (only original value is captured). 
I don't think there is problem using effect. All timers are side-effect, so It does not seems bad to handle timer cancellation inside an effect hook. The idea is to cancel timer as soon as we see that end time is reached. Perhaps you are afraid of concurrency in the event of a very rapid time update?

**Comment by MHA15** [comment]
> Make the test and try to access last time value inside interval: it will not work because of closure (only original value is captured).

about this we can using a ref to store lastValue(see `usePrevious`) 




> The idea is to cancel timer as soon as we see that end time is reached. Perhaps you are afraid of concurrency in the event of a very rapid time update?

yes I'm not sure that it's a good idea to work on react way

**Comment by thibaultboursier** [comment]
@MHA15 Let's go with the **lastTimeRef**. Can you make a PR please?
